# RPM package for ReceiveADSB_WF
# This file is regularly AUTO-GENERATED by the IDE. DO NOT MODIFY.

# By default, the RPM will install to the standard REDHAWK SDR root location (/var/redhawk/sdr)
# You can override this at install time using --prefix /new/sdr/root when invoking rpm (preferred method, if you must)
%{!?_sdrroot: %define _sdrroot /var/redhawk/sdr}
%define _prefix %{_sdrroot}
Prefix: %{_prefix}

Name: ReceiveADSB_WF
Summary: Waveform ReceiveADSB_WF
Version: 1.0.0
Release: 1
License: None
Group: REDHAWK/Waveforms
Source: %{name}-%{version}.tar.gz
# Require the controller whose SPD is referenced
Requires: ADSBdecoder_MR
# Require each referenced component
Requires: ADSBdecoder_MR
BuildArch: noarch
BuildRoot: %{_tmppath}/%{name}-%{version}

%description
This waveform provides an ADSB decoder based upon the malcom robb fork of dump1090 open source project. 

%prep
%setup

%install
%__rm -rf $RPM_BUILD_ROOT
%__mkdir_p "$RPM_BUILD_ROOT%{_prefix}/dom/waveforms/%{name}"
%__install -m 644 ReceiveADSB_WF.sad.xml $RPM_BUILD_ROOT%{_prefix}/dom/waveforms/%{name}/ReceiveADSB_WF.sad.xml

%files
%defattr(-,redhawk,redhawk)
%dir %{_prefix}/dom/waveforms/%{name}
%{_prefix}/dom/waveforms/%{name}/ReceiveADSB_WF.sad.xml
